feat: [EXT-3173] Narrow types for a plain client with adapter
contentful/contentful-management.js pull request #1571
Opened 2022-11-30 12:34 UTC by colomolo

## Summary
Not all cma client methods are available from inside of an app. Thus we're syncing types with cma adapter possibilities:
https://github.com/contentful/experience-packages/blob/master/packages/experience-sdk/src/create-widget-sdk/api/createCMAAdapterApi.ts

2022-12-01 08:42 UTC, Chaoste approved these changes

2022-12-07 11:03 UTC, martin3walker approved these changes
LGTM 👍

2022-12-07 13:38 UTC, andipaetzold requested changes
The name is not quite right. With the adapter, you can still access any method. It is not restricted. At the moment, we only have a single use-case for the adapter, which is apps.

And apps are restricted. So, I'd instead call it `PlainClientAPIViaApp` or similar.

2022-12-07 13:58 UTC, colomolo commented
> And apps are restricted. So, I'd instead call it `PlainClientAPIViaApp` or similar.

Maybe `InAppPlainClientAPI`? Wdyt?

2022-12-13 11:46 UTC, closed without merging