feat: [EXT-3053] implement app metadata methods
contentful/contentful-management.js pull request #972
Opened 2021-09-20 07:40 UTC by Jwhiles

## Summary

## Description

## Motivation and Context

## Checklist (check all before merging)

- [ ] Both unit and integration tests are passing
- [ ] There are no breaking changes
- [ ] Changes are reflected in the documentation

When adding a new method:

- [ ] The new method is exported through the default and plain CMA client
- [ ] All new public types are exported from `./lib/export-types.ts`
- [ ] Added a unit test for the new method
- [ ] Added an integration test for the new method
- [ ] The new method is added to the documentation

2021-09-20 09:36 UTC, Jwhiles commented on lib/entities/app-metadata.ts
> +// TODO should these be exported?
?

2021-09-23 09:04 UTC, andipaetzold requested changes

2021-09-23 09:04 UTC, andipaetzold commented on tsconfig.json
> +      "AppDetails",
maybe also reorder things alphabetical

```suggestion
      "AppSigningSecret",
      "AppDetails",
```

2021-09-23 09:11 UTC, Jwhiles commented on lib/create-organization-api.ts
> +     * Creates or updates an app signing secret
Thanks! 

I thought I got all of these.

2021-09-27 10:19 UTC, andipaetzold commented on lib/create-organization-api.ts
> +     * .then((org) => org.upsertAppDetails('app_definition_id',
It feels strange to me that this method is on org level and not part of the app definition api (https://github.com/contentful/contentful-management.js/blob/master/lib/create-app-definition-api.ts) but we already did the same for the signing secret 🤷

2021-09-27 10:19 UTC, andipaetzold approved these changes

2021-09-28 07:31 UTC, loweisz approved these changes
🚀

2021-09-28 07:52 UTC, merged